export const tiles = [
  { src: "/images/credit-cards.svg", title: "Credit Cards" },
  { src: "/images/home-loans.svg", title: "Home Loans" },
  { src: "/images/health-insurance.svg", title: "Health Insurance" },
  { src: "/images/car-loans.svg", title: "Car Insurance" },
  { src: "/images/transaction-accounts.svg", title: "High-Interest Savings" },
  { src: "/images/electricity.svg", title: "Electricity & Gas" },
  { src: "/images/personal-loans.svg", title: "Personal Loans" },
  { src: "/images/mobile-plans.svg", title: "Mobile Plans" },
  { src: "/images/broadband-nbn-plans.svg", title: "Broadband & NBN" },
  { src: "/images/super-funds.svg", title: "Super Funds" },
  { src: "/images/share-trading.svg", title: "Share Trading" },
  { src: "/images/life-insurance.svg", title: "Life Insurance" },
  { src: "/images/home-loans.svg", title: "Home Insurance" },
  { src: "/images/travel-money.svg", title: "Travel Insurance" },
  { src: "/images/travel-deals.svg", title: "Travel Deals" },
  { src: "/images/bitcoin.svg", title: "Crypto" },
  { src: "/images/car-loans.svg", title: "Car Loans" },
  { src: "/images/pet-insurance.svg", title: "Pet Insurance" },
  { src: "/images/saving-accounts.svg", title: "Transaction Accounts" },
  { src: "/images/intl-money-transfer.svg", title: "Money Transfer" },
  { src: "/images/shopping-deals.svg", title: "Shopping Deals" },
  { src: "/images/internet-tv.svg", title: "Streaming" },
  { src: "/images/business-banking.svg", title: "Business Insurance" },
  { src: "/images/short-term-loans.svg", title: "Short Term Loans" },
];
